module.exports = {
  "US": [{
    "code": "AL",
    "name": "Alabama",
    "country": "US"
  }, {
    "code": "AK",
    "name": "Alaska",
    "country": "US"
  }, {
    "code": "AZ",
    "name": "Arizona",
    "country": "US"
  }, {
    "code": "AR",
    "name": "Arkansas",
    "country": "US"
  }, {
    "code": "CA",
    "name": "California",
    "country": "US"
  }, {
    "code": "CO",
    "name": "Colorado",
    "country": "US"
  }, {
    "code": "CT",
    "name": "Connecticut",
    "country": "US"
  }, {
    "code": "DC",
    "name": "District of Columbia",
    "country": "US"
  }, {
    "code": "DE",
    "name": "Delaware",
    "country": "US"
  }, {
    "code": "FL",
    "name": "Florida",
    "country": "US"
  }, {
    "code": "GA",
    "name": "Georgia",
    "country": "US"
  }, {
    "code": "HI",
    "name": "Hawaii",
    "country": "US"
  }, {
    "code": "ID",
    "name": "Idaho",
    "country": "US"
  }, {
    "code": "IL",
    "name": "Illinois",
    "country": "US"
  }, {
    "code": "IN",
    "name": "Indiana",
    "country": "US"
  }, {
    "code": "IA",
    "name": "Iowa",
    "country": "US"
  }, {
    "code": "KS",
    "name": "Kansas",
    "country": "US"
  }, {
    "code": "KY",
    "name": "Kentucky",
    "country": "US"
  }, {
    "code": "LA",
    "name": "Louisiana",
    "country": "US"
  }, {
    "code": "ME",
    "name": "Maine",
    "country": "US"
  }, {
    "code": "MD",
    "name": "Maryland",
    "country": "US"
  }, {
    "code": "MA",
    "name": "Massachusetts",
    "country": "US"
  }, {
    "code": "MI",
    "name": "Michigan",
    "country": "US"
  }, {
    "code": "MN",
    "name": "Minnesota",
    "country": "US"
  }, {
    "code": "MS",
    "name": "Mississippi",
    "country": "US"
  }, {
    "code": "MO",
    "name": "Missouri",
    "country": "US"
  }, {
    "code": "MT",
    "name": "Montana",
    "country": "US"
  }, {
    "code": "NE",
    "name": "Nebraska",
    "country": "US"
  }, {
    "code": "NV",
    "name": "Nevada",
    "country": "US"
  }, {
    "code": "NH",
    "name": "New Hampshire",
    "country": "US"
  }, {
    "code": "NJ",
    "name": "New Jersey",
    "country": "US"
  }, {
    "code": "NM",
    "name": "New Mexico",
    "country": "US"
  }, {
    "code": "NY",
    "name": "New York",
    "country": "US"
  }, {
    "code": "NC",
    "name": "North Carolina",
    "country": "US"
  }, {
    "code": "ND",
    "name": "North Dakota",
    "country": "US"
  }, {
    "code": "OH",
    "name": "Ohio",
    "country": "US"
  }, {
    "code": "OK",
    "name": "Oklahoma",
    "country": "US"
  }, {
    "code": "OR",
    "name": "Oregon",
    "country": "US"
  }, {
    "code": "PA",
    "name": "Pennsylvania",
    "country": "US"
  }, {
    "code": "RI",
    "name": "Rhode Island",
    "country": "US"
  }, {
    "code": "SC",
    "name": "South Carolina",
    "country": "US"
  }, {
    "code": "SD",
    "name": "South Dakota",
    "country": "US"
  }, {
    "code": "TN",
    "name": "Tennessee",
    "country": "US"
  }, {
    "code": "TX",
    "name": "Texas",
    "country": "US"
  }, {
    "code": "UT",
    "name": "Utah",
    "country": "US"
  }, {
    "code": "VT",
    "name": "Vermont",
    "country": "US"
  }, {
    "code": "VA",
    "name": "Virginia",
    "country": "US"
  }, {
    "code": "WA",
    "name": "Washington",
    "country": "US"
  }, {
    "code": "WV",
    "name": "West Virginia",
    "country": "US"
  }, {
    "code": "WI",
    "name": "Wisconsin",
    "country": "US"
  }, {
    "code": "WY",
    "name": "Wyoming",
    "country": "US"
  }],
  "CA": [{
    "code": "AB",
    "name": "Alberta",
    "country": "CA"
  }, {
    "code": "BC",
    "name": "British Columbia",
    "country": "CA"
  }, {
    "code": "LB",
    "name": "Labrador",
    "country": "CA"
  }, {
    "code": "MB",
    "name": "Manitoba",
    "country": "CA"
  }, {
    "code": "NB",
    "name": "New Brunswick",
    "country": "CA"
  }, {
    "code": "NF",
    "name": "Newfoundland",
    "country": "CA"
  }, {
    "code": "NS",
    "name": "Nova Scotia",
    "country": "CA"
  }, {
    "code": "NU",
    "name": "Nunavut",
    "country": "CA"
  }, {
    "code": "NW",
    "name": "Northwest Territories",
    "country": "CA"
  }, {
    "code": "ON",
    "name": "Ontario",
    "country": "CA"
  }, {
    "code": "PE",
    "name": "Prince Edward Island",
    "country": "CA"
  }, {
    "code": "QC",
    "name": "Quebec",
    "country": "CA"
  }, {
    "code": "SK",
    "name": "Saskatchewen",
    "country": "CA"
  }, {
    "code": "YU",
    "name": "Yukon",
    "country": "CA"
  }],
  "AU": [{
    "name": "Ashmore and Cartier Islands",
    "country": "AU"
  }, {
    "name": "Australian Antarctic Territory",
    "country": "AU"
  }, {
    "code": "ACT",
    "name": "Australian Capital Territory",
    "country": "AU"
  }, {
    "code": "CX",
    "name": "Christmas Island",
    "country": "AU"
  }, {
    "code": "CC",
    "name": "Cocos Islands",
    "alt": ["Keeling Islands"],
    "country": "AU"
  }, {
    "name": "Coral Sea Islands",
    "country": "AU"
  }, {
    "code": "HM",
    "name": "Heard Island and McDonald Islands",
    "country": "AU"
  }, {
    "code": "JBT",
    "name": "Jervis Bay Territory",
    "country": "AU"
  }, {
    "code": "NSW",
    "name": "New South Wales",
    "country": "AU"
  }, {
    "code": "NF",
    "name": "Norfolk Island",
    "country": "AU"
  }, {
    "code": "NT",
    "name": "Northern Territory",
    "country": "AU"
  }, {
    "code": "QLD",
    "name": "Queensland",
    "country": "AU"
  }, {
    "code": "SA",
    "name": "South Australia",
    "country": "AU"
  }, {
    "code": "TAS",
    "name": "Tasmania",
    "country": "AU"
  }, {
    "code": "VIC",
    "name": "Victoria",
    "country": "AU"
  }, {
    "code": "WA",
    "name": "Western Australia",
    "country": "AU"
  }],
  "MX": [{
    "name": "Aguascalientes",
    "code": "AG",
    "alt": ["AGS"],
    "country": "MX"
  }, {
    "name": "Baja California",
    "code": "BC",
    "alt": ["BCN"],
    "country": "MX"
  }, {
    "name": "Baja California Sur",
    "code": "BS",
    "alt": ["BCS"],
    "country": "MX"
  }, {
    "name": "Campeche",
    "code": "CM",
    "alt": ["Camp", "CAM"],
    "country": "MX"
  }, {
    "name": "Chiapas",
    "code": "CS",
    "alt": ["Chis", "CHP"],
    "country": "MX"
  }, {
    "name": "Chihuahua",
    "code": "CH",
    "alt": ["Chih", "CHH"],
    "country": "MX"
  }, {
    "name": "Coahuila",
    "code": "MX",
    "alt": ["Coah", "COA"],
    "country": "MX"
  }, {
    "name": "Colima",
    "code": "CL",
    "alt": ["COL"],
    "country": "MX"
  }, {
    "name": "Federal District",
    "code": "DF",
    "alt": ["DIF"],
    "country": "MX"
  }, {
    "name": "Durango",
    "code": "DG",
    "alt": ["Dgo", "DUR"],
    "country": "MX"
  }, {
    "name": "Guanajuato",
    "code": "GT",
    "alt": ["Gto", "GUA"],
    "country": "MX"
  }, {
    "name": "Guerrero",
    "code": "GR",
    "alt": ["Gro", "GRO"],
    "country": "MX"
  }, {
    "name": "Hidalgo",
    "code": "HG",
    "alt": ["Hgo", "HID"],
    "country": "MX"
  }, {
    "name": "Jalisco",
    "code": "JA",
    "alt": ["Jal", "JAL"],
    "country": "MX"
  }, {
    "name": "Mexico",
    "code": "ME",
    "alt": ["Edomex", "MEX"],
    "country": "MX"
  }, {
    "name": "Michoacán",
    "code": "MI",
    "alt": ["Mich", "MIC"],
    "country": "MX"
  }, {
    "name": "Morelos",
    "code": "MO",
    "alt": ["Mor", "MOR"],
    "country": "MX"
  }, {
    "name": "Nayarit",
    "code": "NA",
    "alt": ["Nay", "NAY"],
    "country": "MX"
  }, {
    "name": "Nuevo León",
    "code": "NL",
    "alt": ["NLE"],
    "country": "MX"
  }, {
    "name": "Oaxaca",
    "code": "OA",
    "alt": ["Oax", "OAX"],
    "country": "MX"
  }, {
    "name": "Puebla",
    "code": "PU",
    "alt": ["Pue", "PUE"],
    "country": "MX"
  }, {
    "name": "Querétaro",
    "code": "QE",
    "alt": ["Qro", "QUE"],
    "country": "MX"
  }, {
    "name": "Quintana Roo",
    "code": "QR",
    "alt": ["Q Roo", "ROO"],
    "country": "MX"
  }, {
    "name": "San Luis Potosí",
    "code": "SL",
    "alt": ["SLP"],
    "country": "MX"
  }, {
    "name": "Sinaloa",
    "code": "SI",
    "alt": ["SIN"],
    "country": "MX"
  }, {
    "name": "Sonora",
    "code": "SO",
    "alt": ["SON"],
    "country": "MX"
  }, {
    "name": "Tabasco",
    "code": "TB",
    "alt": ["TAB"],
    "country": "MX"
  }, {
    "name": "Tamaulipas",
    "code": "TM",
    "alt": ["Tamps", "TAM"],
    "country": "MX"
  }, {
    "name": "Tlaxcala",
    "code": "TL",
    "alt": ["Tlax", "TLA"],
    "country": "MX"
  }, {
    "name": "Veracruz",
    "code": "VE",
    "alt": ["VER"],
    "country": "MX"
  }, {
    "name": "Yucatán",
    "code": "YU",
    "alt": ["YUC"],
    "country": "MX"
  }, {
    "name": "Zacatecas",
    "code": "ZA",
    "alt": ["ZAC"],
    "country": "MX"
  }],
  "CN": [{
    "name": "重庆",
    "country": "CN"
  }, {
    "name": "黑龙江",
    "country": "CN"
  }, {
    "name": "吉林",
    "country": "CN"
  }, {
    "name": "海南",
    "country": "CN"
  }, {
    "name": "北京",
    "country": "CN"
  }, {
    "name": "辽宁",
    "country": "CN"
  }, {
    "name": "内蒙古",
    "country": "CN"
  }, {
    "name": "西藏",
    "country": "CN"
  }, {
    "name": "青海",
    "country": "CN"
  }, {
    "name": "宁夏",
    "country": "CN"
  }, {
    "name": "新疆",
    "country": "CN"
  }, {
    "name": "甘肃",
    "country": "CN"
  }, {
    "name": "河北",
    "country": "CN"
  }, {
    "name": "河南",
    "country": "CN"
  }, {
    "name": "湖北",
    "country": "CN"
  }, {
    "name": "湖南",
    "country": "CN"
  }, {
    "name": "山东",
    "country": "CN"
  }, {
    "name": "江苏",
    "country": "CN"
  }, {
    "name": "安徽",
    "country": "CN"
  }, {
    "name": "山西",
    "country": "CN"
  }, {
    "name": "陕西",
    "country": "CN"
  }, {
    "name": "四川",
    "country": "CN"
  }, {
    "name": "云南",
    "country": "CN"
  }, {
    "name": "贵州",
    "country": "CN"
  }, {
    "name": "浙江",
    "country": "CN"
  }, {
    "name": "福建",
    "country": "CN"
  }, {
    "name": "广西",
    "country": "CN"
  }, {
    "name": "上海",
    "country": "CN"
  }, {
    "name": "天津",
    "country": "CN"
  }, {
    "name": "香港",
    "country": "CN"
  }, {
    "name": "澳门",
    "country": "CN"
  }, {
    "name": "台湾",
    "country": "CN"
  }, {
    "name": "江西",
    "country": "CN"
  }, {
    "name": "广东",
    "country": "CN"
  }],
  "GB": [{
    "name": "Avon",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Bedfordshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Berkshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Borders",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Bristol",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Buckinghamshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Cambridgeshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Channel Islands",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Cheshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Cleveland",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Cornwall",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Cumbria",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Derbyshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Devon",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Dorset",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Durham",
    "country": "GB",
    "region": "England"
  }, {
    "name": "East Riding of Yorkshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "East Sussex",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Essex",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Gloucestershire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Greater Manchester",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Hampshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Herefordshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Hertfordshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Humberside",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Isle of Man",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Isle of Wight",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Isles of Scilly",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Kent",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Lancashire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Leicestershire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Lincolnshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "London",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Merseyside",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Middlesex",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Norfolk",
    "country": "GB",
    "region": "England"
  }, {
    "name": "North Yorkshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Northamptonshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Northumberland",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Nottinghamshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Oxfordshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Rutland",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Shropshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Somerset",
    "country": "GB",
    "region": "England"
  }, {
    "name": "South Yorkshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Staffordshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Suffolk",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Surrey",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Tyne and Wear",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Warwickshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "West Midlands",
    "country": "GB",
    "region": "England"
  }, {
    "name": "West Sussex",
    "country": "GB",
    "region": "England"
  }, {
    "name": "West Yorkshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Wiltshire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Worcestershire",
    "country": "GB",
    "region": "England"
  }, {
    "name": "Antrim",
    "country": "GB",
    "region": "Northern Ireland"
  }, {
    "name": "Down",
    "country": "GB",
    "region": "Northern Ireland"
  }, {
    "name": "Fermanagh",
    "country": "GB",
    "region": "Northern Ireland"
  }, {
    "name": "Londonderry",
    "country": "GB",
    "region": "Northern Ireland"
  }, {
    "name": "Tyrone",
    "country": "GB",
    "region": "Northern Ireland"
  }, {
    "name": "Aberdeen City",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Aberdeenshire",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Angus",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Argyll and Bute",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Armagh",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Carmarthenshire",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Clackmannan",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Dumfries and Galloway",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "East Ayrshire",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "East Dunbartonshire",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "East Lothian",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "East Renfrewshire",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Edinburgh City",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Falkirk",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Fife",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Glasgow",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Highland",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Inverclyde",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Midlothian",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Moray",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "North Ayrshire",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "North Lanarkshire",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Orkney",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Perthshire and Kinross",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Renfrewshire",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Roxburghshire",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Shetland",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "South Ayrshire",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "South Lanarkshire",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Stirling",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "West Dunbartonshire",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "West Lothian",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Western Isles",
    "country": "GB",
    "region": "Scotland"
  }, {
    "name": "Blaenau Gwent",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Bridgend",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Caerphilly",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Cardiff",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Ceredigion",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Conwy",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Denbighshire",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Flintshire",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Gwynedd",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Isle of Anglesey",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Merthyr Tydfil",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Monmouthshire",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Neath Port Talbot",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Newport",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Pembrokeshire",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Powys",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Rhondda Cynon Taff",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Swansea",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "The Vale of Glamorgan",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Torfaen",
    "country": "GB",
    "region": "Wales"
  }, {
    "name": "Wrexham",
    "country": "GB",
    "region": "Wales"
  }],
  "DE": [{
    "code": "BW",
    "name": "Baden-Württemberg",
    "country": "DE"
  }, {
    "code": "BY",
    "name": "Bayern",
    "country": "DE"
  }, {
    "code": "BE",
    "name": "Berlin",
    "country": "DE"
  }, {
    "code": "BB",
    "name": "Brandenburg",
    "country": "DE"
  }, {
    "code": "HB",
    "name": "Bremen",
    "country": "DE"
  }, {
    "code": "HH",
    "name": "Hamburg",
    "country": "DE"
  }, {
    "code": "HE",
    "name": "Hessen",
    "country": "DE"
  }, {
    "code": "MV",
    "name": "Mecklenburg-Vorpommern",
    "country": "DE"
  }, {
    "code": "NI",
    "name": "Niedersachsen",
    "country": "DE"
  }, {
    "code": "NW",
    "name": "Nordrhein-Westfalen",
    "country": "DE"
  }, {
    "code": "RP",
    "name": "Rheinland-Pfalz",
    "country": "DE"
  }, {
    "code": "SL",
    "name": "Saarland",
    "country": "DE"
  }, {
    "code": "SN",
    "name": "Sachsen",
    "country": "DE"
  }, {
    "code": "ST",
    "name": "Sachsen-Anhalt",
    "country": "DE"
  }, {
    "code": "SH",
    "name": "Schleswig-Holstein",
    "country": "DE"
  }, {
    "code": "TH",
    "name": "Thüringen",
    "country": "DE"
  }]
};
